version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine3.17
    volumes:
      - $HOME/postgresql/space:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: